// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amthhpolmiyckahxxtxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtdGhocG9sbWl5Y2thaHh4dHh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDQyMjIsImV4cCI6MjA2NTU4MDIyMn0.r5ZLaBWhlzTyLFUGsv6EN0G7_WBYZs6ove9kiEhROAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);